id: AD0EC38EC
base_file: f3761.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:05:18.628714
  last_modified_at: 2022-05-30 21:05:18.628723
